import { CourseDTO } from "../CourseDTO.dto";
import { httpServiceMock, ResponseResult } from "@core/service";

class CourseContext {
  getCourseById(id: string): ResponseResult<CourseDTO.ICourse> {
    return httpServiceMock<CourseDTO.ICourse>(
      {
        id: id,
        title: "Драйверы - 2021",
        desc: "Каждое подразделение нашей Компании ставит цели (драйверы) на год для продуктивной деятельности. Рады представить вашему вниманию Драйверы-2021 года. Уверены, что информация будет способствовать единому пониманию пути развития Компании в текущем году",
        img: '/download_file.html?object_id=1',
        likes: 3,
        comments: 10,
        time_to_pass: "45 мин",
        url: "/_wt/123",
        info: {
          reviews: [
            {
              person_id: "123",
              person_fullname: "Чурсина Мария Юрьевна ",
              img: '',
              person_position_name: "Торговый представитель по развитию",
              rate: 4,
              max_rate: 5,
              likes: 17,
              min_text:
                "Курс даст информацию о преимуществах работы в Компании, ее истории.",
              max_text:
                "Целью моей учёбы было получение образования для саморазвития и получения новых знаний. Дистанционная форма обучения на мой взгляд очень удобна в плане совмещения с работой. Материалы для обучения были в свободном доступе, что легко позволило получить необходимую информацию для окончания учёбы. Система тестирования тоже порадовала тем, что можно было неограниченно проверять свои знания в любое время.",
            },
            {
              person_id: "1234",
              person_fullname: "Петрова Ирина Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 2,
              max_rate: 5,
              likes: 1,
              min_text: "Курс не очень.",
              max_text: "Как-то ну вообще не очень.",
            },
            {
              person_id: "12345",
              person_fullname: "Игнатьева Оксана Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 2,
              likes: 78,
              max_rate: 5,
              min_text: "Курс не очень.",
              max_text: "Как-то ну вообще не очень.",
            },
            {
              person_id: "12345687",
              person_fullname: "Чвак Оксана Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              likes: 3,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "123456",
              person_fullname: "Шыврина Оксана Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              likes: 11,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "1234567",
              person_fullname: "Рогозина Валентина Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              likes: 50,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "1234568",
              person_fullname: "Петров Петр Витальевич ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              likes: 100,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "123456998",
              person_fullname: "Васильева Нина Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "12345698",
              person_fullname: "Носорогова Людмила Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "12345699",
              person_fullname: "Вострик Вера Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "123456999",
              person_fullname: "Злобова Зоя Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "12345699996",
              person_fullname: "Щука Зоя Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
            {
              person_id: "1234569999",
              person_fullname: "Карась Зоя Витальевна ",
              img: '',
              person_position_name: "Менеджер",
              rate: 5,
              max_rate: 5,
              min_text: "Курс отличныыыый.",
              max_text: "Ну вообще отличныыыый.",
            },
          ],
        },
      },
    );
  }
}

export const courseContext = new CourseContext();
