// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'likes': string;
  'personInfo': string;
  'personInfoWrapper': string;
  'personPosition': string;
  'reviewAvatar': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
