// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkBox': string;
  'email': string;
  'input': string;
  'person': string;
  'position': string;
  'tableMobile': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
