// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'courses': string;
  'courses__head': string;
  'courses__inner': string;
  'courses__item': string;
  'courses__item-box': string;
  'courses__item-count': string;
  'courses__item-counter': string;
  'courses__item-descr': string;
  'courses__item-footer': string;
  'courses__item-image': string;
  'courses__item-image--mobile': string;
  'courses__item-inner': string;
  'courses__item-link': string;
  'courses__item-personal': string;
  'courses__item-progress': string;
  'courses__item-progressBar': string;
  'courses__item-progressText': string;
  'courses__item-title': string;
  'courses__items': string;
  'courses__title': string;
  'courses__toggler': string;
  'courses__toggler-button': string;
  'desc': string;
  'mob': string;
  'open': string;
  'progress-bar-length': string;
  'reviews__item-count': string;
}
export const cssExports: CssExports;
export default cssExports;
