// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'card': string;
  'flag': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
