import { CollaboratorDTO } from '@src/interfaces/collaborators.interface';

export const collaboratorData: CollaboratorDTO.IPerson[] = [
    {
        id: '1',
        fullname: 'Абидов Астемир Русланович',
        code: '20061',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '2',
        fullname: 'Волошина Елена Александровна',
        code: '20062',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '3',
        fullname: 'Евстратова Елена Вячеславовна',
        code: '20063',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '4',
        fullname: 'Кожичкин Владимир Владимирович',
        code: '20064',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '5',
        fullname: 'Никитин Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '6',
        fullname: 'Кукуев Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '7',
        fullname: 'Дорина Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '8',
        fullname: 'Абрамов Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '9',
        fullname: 'Зигмунд Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
    {
        id: '10',
        fullname: 'Лапин Виталий Витальевич',
        code: '20065',
        org_name: 'Группа внедрения электронного обучения ОРиВДИ',
        org_id: '1',
        email: 'aar211@komus.net',
    },
]