import { CourseDTO } from "@src/interfaces/course.interface";

export const coursesData: CourseDTO.ICourse[] = [
  {
    id: "6984770925734410330",
    progress: 51,
    firstCategory: "Курсы",
    categories: "fail",
    title: "Ассортимент-курс Обувь",
    description: "fail_1",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: "7011083487926703687",
    progress: 51,
    firstCategory: "Курсы",
    categories: "active",
    title: "5 секретов победы в Конкурсной сделке по РО и СИЗ",
    description: "fail_2",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: "6499733113815984573",
    progress: 51,
    firstCategory: "Курсы",
    categories: "active",
    title: "Конкурсные продажи. Особые требования заказчиков к поставщикам и как с ними работать.",
    description: "fail_3",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 4,
    progress: 51,
    firstCategory: "Курсы",
    categories: "fail",
    title: "WELCOME",
    description: "fail_4",
    likes: 5,
    comments: 0,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },

  {
    id: 5,
    progress: 100,
    firstCategory: "Курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 6,
    progress: 99,
    firstCategory: "Курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 7,
    progress: 98,
    firstCategory: "Курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 8,
    progress: 97,
    firstCategory: "Курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 9,
    progress: 11,
    firstCategory: "Курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "35 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
  {
    id: 10,
    progress: 51,
    firstCategory: "Рекомендованные курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "45 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },

  {
    id: 11,
    progress: 11,
    firstCategory: "Рекомендованные курсы",
    categories: "active",
    title: "WELCOME",
    description:
      "что начало повседневной работы по формированию позиции позволяет...",
    likes: 5,
    comments: 11,
    estimate: "35 мин.",
    img: "/komus_num/app/images/courses.png",
    url: "_wt/7011083487926703687",
    tags: ["Новому сотруднику"],
  },
];
