// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'hideCircle': string;
  'likes': string;
  'loadCircle': string;
  'loadCourseCard': string;
  'loadText': string;
  'minText': string;
  'reviewAvatar': string;
  'root': string;
  'rootWrapper': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
