// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockTitle': string;
  'datePicker': string;
  'paginationWrapper': string;
  'root': string;
  'searchBlock': string;
  'searchWrapper': string;
  'tableWrapper': string;
  'timeBlock': string;
  'timeWrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
