// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'courseCard': string;
  'courseDesc': string;
  'courseImg': string;
  'courseTitle': string;
  'footer': string;
  'footerBtns': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
