// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fill': string;
  'isEditable': string;
  'raiting': string;
  'star': string;
}
export const cssExports: CssExports;
export default cssExports;
